# Generated by Django 4.1.7 on 2023-03-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=10)),
                ('friend_age', models.IntegerField()),
                ('friend_bigo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
